# Generated by Django 5.0.4 on 2024-06-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('cost_per_unit', models.PositiveIntegerField()),
                ('all_restaurants', models.BooleanField(default=True)),
            ],
        ),
    ]
