# Generated by Django 5.0.4 on 2024-06-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiter_shift',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
